version: '3.8'

services:
  project-manager-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - JAR_FILE=*.jar
    container_name: project-manager-backend   
    image: project-manager-backend:latest
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/projectmanagerdb         
    ports:
      - 8090:8090   
    networks:
    - project-manager-network
  postgres_db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projectmanagerdb
    ports:
      - "5434:5432"
    volumes:
        #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./data/pgsql:/var/lib/postgresql/data
      - ./dbfiles/projectmanager.sql:/docker-entrypoint-initdb.d/projectmanager.sql
    networks:
    - project-manager-network
networks:  
    project-manager-network:
        driver: bridge       
  